// features/ai/config/diagnosis.config.ts

import { DiagnosisModifierType } from "../types/diagnosis.types";

export const ENGINE_CONFIG = {
  // 💡 NEW: Upgrade ke V5.9.0 (Pre-Reasoning Engine)
  ENGINE_VERSION: "v5.9.0",
  RULESET_VERSION: "v2026.07",
  
  DEFAULT_RECALL_WEIGHT: 0.65,
  DEFAULT_PRECISION_WEIGHT: 0.25,
  DEFAULT_COVERAGE_WEIGHT: 0.10,
  
  MAX_HALLMARK_BONUS: 0.10,
  PRIOR_ACTIVATION_THRESHOLD: 40,
  MAX_PRIOR_BONUS: 0.05,
  MAX_MODIFIER_BONUS: 0.05,
  
  SQRT_PENALTY_FACTOR: 7.5,
  LIMITER_LEVEL_1: 70, 
  LIMITER_LEVEL_2: 55, 
  LIMITER_LEVEL_3: 40,
  
  MIN_CONFIDENCE_THRESHOLD: 20,
  DIFFERENTIAL_GAP_TOLERANCE: 5,
  DIFFERENTIAL_OVERLAP_THRESHOLD: 0.40, 

  XAI_RECALL_HIGH_THRESHOLD: 0.75,
  XAI_PRECISION_HIGH_THRESHOLD: 0.75,
  XAI_PRECISION_LOW_THRESHOLD: 0.40,
  XAI_MODIFIER_HIGH_THRESHOLD: 7.0,
  XAI_ALIEN_PENALTY_CRITICAL: 15.0,

  MODIFIER_WEIGHTS: {
    SPECIES_GENETICS: 0.4,
    WATER_QUALITY: 0.3,
    TEMPERATURE: 0.2,
    STRESS: 0.1
  } as Record<DiagnosisModifierType, number>,

  SYNERGY_MULTIPLIERS: {
    WATER_AND_TEMP: 1.5,
    STRESS_AND_WATER: 1.2
  }
};